@hostname = localhost
@port = 3003
@host = {{hostname}}:{{port}}

POST http://{{host}}/api/users
content-type: application/json

{ 
  "username": "root",
  "name": "inverimus",
  "password" : "secretpassword"
}

###

POST http://{{host}}/api/users
content-type: application/json

{ 
  "username": "john",
  "name": "johnny boy",
  "password" : "secretpassword"
}

###

GET http://{{host}}/api/users